services:
  postgres:
    image: postgres:18
    container_name: ahlipanggilan-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ahlipanggilan
      POSTGRES_USER: ahlipanggilan
      POSTGRES_PASSWORD: ahlipanggilan
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - ahlipanggilan
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ahlipanggilan']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: ahlipanggilan-redis
    restart: unless-stopped
    profiles:
      - cache
      - test
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - ahlipanggilan
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: ahlipanggilan-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: infrastructure/docker/api/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      APP_ENV: development
      DATABASE_URL: postgres://ahlipanggilan:ahlipanggilan@postgres:5432/ahlipanggilan
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ahlipanggilan

  web:
    container_name: ahlipanggilan-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: infrastructure/docker/web/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/dist
      - /app/apps/web/node_modules/.astro
    ports:
      - '4321:4321'
    environment:
      APP_ENV: development
      API_URL: http://api:3000
    depends_on:
      api:
        condition: service_started
    networks:
      - ahlipanggilan

  nginx:
    image: nginx:alpine
    container_name: ahlipanggilan-nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./infrastructure/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
    networks:
      - ahlipanggilan

  mailpit:
    image: axllent/mailpit:latest
    container_name: ahlipanggilan-mailpit
    restart: unless-stopped
    profiles:
      - mail
      - test
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - ahlipanggilan

  test-db:
    image: postgres:18
    container_name: ahlipanggilan-test-db
    profiles:
      - test
    environment:
      POSTGRES_DB: ahlipanggilan_test
      POSTGRES_USER: ahlipanggilan
      POSTGRES_PASSWORD: ahlipanggilan
    ports:
      - '5433:5432'
    networks:
      - ahlipanggilan
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ahlipanggilan -d ahlipanggilan_test']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  uploads_data:

networks:
  ahlipanggilan:
    driver: bridge
