type: counter
name: ahlipanggilan/api-404-storm
description: 'Enumerasi endpoint API (404 storm pada /api/*)'
filter: |
  evt.Parsed.verb == 'GET'
  && evt.Parsed.http_path startsWith '/api/'
  && evt.Parsed.http_status == '404'
leakspeed: 60s
capacity: 30
groupby: evt.Parsed.source_ip
labels:
  type: scan
  service: ahlipanggilan
  behavior: 'http:scan'
  severity: critical

decisions:
  - type: ban
    duration: 10m
