type: leaky
name: ahlipanggilan/api-404-storm
description: 'Enumerasi endpoint API (404 storm pada /api/*)'
filter: |
  evt.Parsed.verb == 'GET'
  && evt.Parsed.http_path matches '^/api/'
  && evt.Parsed.http_status == '404'
leakspeed: 60s
capacity: 29
groupby: evt.Parsed.source_ip
labels:
  type: scan
  service: ahlipanggilan
  behavior: 'http:scan'
  severity: critical
  remediation: true
