import { Hono } from 'hono';
import { healthRouter } from './health.ts';
import { authRouter } from './auth.ts';
import { bookingsRouter } from './bookings.ts';
import { servicesRouter } from './services.ts';
import { serviceCategoriesRouter } from './service-categories.ts';
import { customersRouter } from './customers.ts';
import { addressesRouter } from './addresses.ts';
import { partnersRouter } from './partners.ts';
import { paymentsRouter } from './payments.ts';
import { reviewsRouter } from './reviews.ts';
import { complaintsRouter } from './complaints.ts';
import { companiesRouter } from './companies.ts';
import { notificationsRouter } from './notifications.ts';
import { dashboardRouter } from './admin/dashboard.ts';
import { adminServicesRouter } from './admin/services.ts';
import { adminServiceCategoriesRouter } from './admin/service-categories.ts';
import { articlesRouter } from './articles.ts';
import { mediaRouter } from './media.ts';
import { adminArticlesRouter } from './admin/articles.ts';
import { adminUsersRouter } from './admin/users.ts';
import { adminSettingsRouter } from './admin/settings.ts';

const router = new Hono();

router.route('/health', healthRouter);
router.route('/auth', authRouter);
router.route('/bookings', bookingsRouter);
router.route('/services', servicesRouter);
router.route('/service-categories', serviceCategoriesRouter);
router.route('/customers', customersRouter);
router.route('/addresses', addressesRouter);
router.route('/partners', partnersRouter);
router.route('/payments', paymentsRouter);
router.route('/reviews', reviewsRouter);
router.route('/complaints', complaintsRouter);
router.route('/companies', companiesRouter);
router.route('/notifications', notificationsRouter);
router.route('/admin/dashboard', dashboardRouter);
router.route('/admin/services', adminServicesRouter);
router.route('/admin/service-categories', adminServiceCategoriesRouter);
router.route('/articles', articlesRouter);
router.route('/admin/articles', adminArticlesRouter);
router.route('/admin/users', adminUsersRouter);
router.route('/admin/settings', adminSettingsRouter);
router.route('/media', mediaRouter);

export { router as apiRouter };
