import { vi } from 'vitest';

// Build table name exports (must be inline — no imports)
const TABLE_NAMES = [
  'users',
  'customerProfiles',
  'partnerProfiles',
  'companies',
  'addresses',
  'serviceCategories',
  'services',
  'orders',
  'orderItems',
  'assignments',
  'payments',
  'reviews',
  'complaints',
  'notifications',
  'auditLogs',
  'media',
  'orderMedia',
  'seoMetadata',
  'systemSettings',
  'orderStatusHistory',
  'companyUsers',
  'branches',
  'refreshTokens',
  'passwordResets',
  'partnerSkills',
  'partnerDocuments',
  'articles',
  'articleCategories',
  'contracts',
  'invoices',
  'faq',
  'corporateInquiries',
  'usersRelations',
  'customerProfilesRelations',
  'partnerProfilesRelations',
  'companiesRelations',
  'companyUsersRelations',
  'branchesRelations',
  'serviceCategoriesRelations',
  'servicesRelations',
  'ordersRelations',
  'orderItemsRelations',
  'assignmentsRelations',
  'paymentsRelations',
  'reviewsRelations',
  'complaintsRelations',
  'notificationsRelations',
  'auditLogsRelations',
  'partnerSkillsRelations',
  'partnerDocumentsRelations',
  'mediaRelations',
  'orderMediaRelations',
  'articlesRelations',
  'articleCategoriesRelations',
  'contractsRelations',
  'invoicesRelations',
];
const exps: Record<string, unknown> = {};
for (const n of TABLE_NAMES) exps[n] = {};
vi.stubGlobal('__TABLE_EXPORTS', exps);
