// =============================================================================
// Analytics Platform — Event Registry
// =============================================================================
// Single source of truth for ALL analytics events.
// Every event MUST be registered here before use.
// No event should exist outside this registry.
// =============================================================================

import type { EventCategory, EventDefinition } from '../types.ts';

// ── Event Registry Type (auto-generated) ──────────────────────────
// Maps event name → expected properties (type-safe)
// AUTO-GENERATED by `pnpm analytics:typegen:write` from events/index.ts
// Do NOT edit manually — edit events/index.ts and regenerate.
export type { EventRegistry } from './events.generated.ts';

// ── Definitions Store ─────────────────────────────────────────────
// Internal store of event metadata (not visible to components)

const definitions = new Map<string, EventDefinition>();

export function registerEventDefinition(def: EventDefinition): void {
  if (definitions.has(def.name)) {
    console.warn(`[Analytics] Event "${def.name}" already registered. Overwriting.`);
  }
  definitions.set(def.name, def);
}

export function getEventDefinition(name: string): EventDefinition | undefined {
  return definitions.get(name);
}

export function getAllEventDefinitions(): EventDefinition[] {
  return Array.from(definitions.values());
}

export function getEventsByCategory(category: EventCategory): EventDefinition[] {
  return Array.from(definitions.values()).filter((d) => d.category === category);
}

export function getEventsByStatus(status: 'active' | 'deprecated' | 'removed'): EventDefinition[] {
  return Array.from(definitions.values()).filter((d) => d.status === status);
}
