// =============================================================================
// Analytics Platform — Event Registry Interface (AUTO-GENERATED)
// =============================================================================
//
// This file is AUTO-GENERATED by pnpm analytics:typegen --write
// Do NOT edit manually. Any manual changes will be overwritten.
//
// Generated from:
//   - 80 event definitions in events/index.ts
//   - 72 property definitions in properties/index.ts
//   - 80 active events
//   - 0 deprecated events
//   - 0 removed events
//
// Maps event name → expected properties (type-safe)
// This is the contract that track() uses for compile-time validation.
// =============================================================================

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface EventRegistry {
  // ── Authentication ───────────────────────────────────────
  login_start: { method: string };
  login_success: {
    user_id: string;
    role: string;
  };
  login_failed: { reason: string };
  logout: {};
  password_reset_request: { email_hash: string };
  password_reset_complete: {};
  register_start: { method: string };
  register_complete: {
    user_id: string;
    role: string;
  };

  // ── Booking ───────────────────────────────────────
  booking_start: {
    service_id: string;
    customer_type: 'guest' | 'registered';
  };
  booking_submit: {
    service_id: string;
    booking_id: string;
    customer_type: 'guest' | 'registered';
  };
  booking_form_step: {
    step: number;
    step_name: string;
    booking_id?: string;
  };
  booking_list_view: { result_count: number };
  booking_confirm: { booking_id: string };
  booking_status_view: {
    booking_id: string;
    status: string;
  };
  booking_assign: {
    booking_id: string;
    partner_id: string;
  };
  booking_cancel: {
    booking_id: string;
    reason?: string;
  };

  // ── Cms ───────────────────────────────────────
  article_view: {
    article_id: string;
    category: string;
    slug: string;
  };
  article_list_view: {
    page: string;
    category?: string;
  };
  faq_view: { category?: string };
  faq_open: {
    faq_id: string;
    question: string;
    category: string;
  };

  // ── Complaint ───────────────────────────────────────
  complaint_start: { booking_id: string };
  complaint_submit: {
    complaint_id: string;
    booking_id: string;
    category: string;
  };

  // ── Corporate ───────────────────────────────────────
  corporate_landing_view: {};
  inquiry_start: {};
  inquiry_submit: {
    company_name: string;
    service_interest: string;
    industry?: string;
    employees?: number;
  };
  corporate_dashboard_view: {};

  // ── Dashboard ───────────────────────────────────────
  dashboard_view: {
    role: string;
    section: string;
  };
  dashboard_filter: {
    role: string;
    filter: string;
    value: number;
  };
  dashboard_export: {
    role: string;
    type: string;
    row_count: number;
  };

  // ── Engagement ───────────────────────────────────────
  page_engagement: {
    duration: number;
    page: string;
    interaction_count: number;
  };
  scroll_depth: {
    depth: number;
    page: string;
  };
  session_start: {
    referrer?: string;
    utm_source?: string;
    utm_medium?: string;
    utm_campaign?: string;
  };
  session_end: {
    duration: number;
    page_views: number;
    page: string;
  };
  visibility_change: {
    hidden: boolean;
    duration: number;
    previous_visibility?: string;
  };

  // ── Error ───────────────────────────────────────
  page_404: {
    path: string;
    referrer?: string;
  };
  api_error: {
    endpoint: string;
    status: string;
    method: string;
  };
  error_boundary_caught: {
    component: string;
    error: string;
  };
  page_500: {
    path: string;
    error?: string;
  };

  // ── Landing ───────────────────────────────────────
  hero_view: { duration: number };
  hero_cta_click: {
    cta: string;
    position: number;
  };
  service_category_click: {
    category: string;
    position: number;
  };
  testimonials_view: { count: number };
  partner_cta_click: { source: string };
  corporate_cta_click: { source: string };
  footer_cta_click: {
    cta: string;
    section: string;
  };
  whatsapp_click: {
    source: string;
    page: string;
  };
  service_view: {
    service_id: string;
    category: string;
    slug: string;
  };
  service_book_click: {
    service_id: string;
    category: string;
    price: number;
  };

  // ── Navigation ───────────────────────────────────────
  pageview: {
    url: string;
    title: string;
    referrer?: string;
  };
  navigation_click: {
    destination: string;
    label: string;
    section?: string;
  };
  cta_click: {
    section: string;
    cta: string;
    position: number;
    page: string;
  };
  outbound_link_click: {
    url: string;
    text: string;
    destination: string;
  };
  download_click: {
    file: string;
    type: string;
    size?: number;
  };
  history_navigation: {
    from: string;
    to: string;
    method: string;
  };

  // ── Partner ───────────────────────────────────────
  partner_register_start: {};
  partner_register_form_step: {
    step: number;
    step_name: string;
  };
  partner_register_complete: { partner_id: string };
  partner_dashboard_view: {};
  partner_job_accept: {
    assignment_id: string;
    booking_id: string;
  };
  partner_job_reject: {
    assignment_id: string;
    booking_id: string;
    reason: string;
  };
  partner_availability_update: { status: string };

  // ── Payment ───────────────────────────────────────
  payment_submit: {
    booking_id: string;
    amount: number;
    method: string;
  };
  payment_start: {
    booking_id: string;
    amount: number;
    method: string;
  };
  payment_success: {
    booking_id: string;
    amount: number;
    method: string;
    payment_id: string;
  };
  payment_failed: {
    booking_id: string;
    amount: number;
    method: string;
    error?: string;
  };

  // ── Performance ───────────────────────────────────────
  lcp_measure: {
    value: number;
    element?: string;
  };
  cls_measure: { value: number };
  fid_measure: { value: number };
  ttfb_measure: { value: number };

  // ── Review ───────────────────────────────────────
  review_start: { booking_id: string };
  review_submit: {
    booking_id: string;
    rating: 1 | 2 | 3 | 4 | 5;
  };

  // ── Search ───────────────────────────────────────
  search_result: {
    query: string;
    result_count: number;
    has_results: boolean;
  };
  search_start: { query?: string };
  search_filter: {
    filter: string;
    value: number;
    result_count: number;
  };

  // ── Seo ───────────────────────────────────────
  seo_meta_update: {
    entity_type: string;
    entity_id: string;
  };
  seo_redirect_create: {
    source: string;
    destination: string;
  };
  seo_sitemap_generate: { page_count: number };

  // ── Service ───────────────────────────────────────
  service_detail_view: {
    service_id: string;
    category: string;
    slug: string;
  };
  service_faq_open: {
    service_id: string;
    faq_id: string;
    question: string;
  };
  service_gallery_view: {
    service_id: string;
    image_count: number;
  };
}
