#!/usr/bin/env tsx
// =============================================================================
// Analytics Platform — Type Generator
// =============================================================================
//
// Generates the EventRegistry TypeScript interface from the runtime event
// and property definitions. This ensures EventRegistry is ALWAYS in sync
// with actual registered event definitions.
//
// Usage:
//   pnpm analytics:typegen          # preview to stdout
//   pnpm analytics:typegen --write  # overwrite src/registry/events.ts
//
// The generated file is the SOURCE OF TRUTH for:
//   - Available event names (as union type keys)
//   - Required & optional properties per event (as Record type values)
//   - Type safety for track() at compile time
//
// =============================================================================

import { mkdirSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

// ── Bootstrap: load all event and property definitions ──────────────
// This registers all events & properties via module side-effects.
await import('../src/events/index.ts');
await import('../src/properties/index.ts');

const { getAllEventDefinitions } = await import('../src/registry/events.ts');

const { getAllPropertyDefinitions } = await import('../src/registry/properties.ts');

// ── Context-Independent Property Keys ──────────────────────────────
// Properties that ALWAYS have the same type regardless of event context.
// These are safe to narrow with allowedValues.
// Properties shared across contexts (like "method", "status") use base types only.
const SAFE_LITERAL_PROPS = new Set([
  'customer_type',
  'rating',
  'hidden',
  'utm_source',
  'utm_medium',
  'utm_campaign',
]);

// ── Helpers ─────────────────────────────────────────────────────────

function toPascalCase(str: string): string {
  return str
    .split('_')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/**
 * Determine the TypeScript type string for a property.
 * - For SAFE_LITERAL_PROPS with allowedValues: emit literal union
 * - For ALL other properties: use base TypeScript type (string, number, boolean)
 *
 * This avoids the issue of shared property keys (like "method", "status")
 * being overwritten by different event contexts in the property registry.
 */
function propertyToTypeString(
  key: string,
  propertyDef: { type: string; allowedValues?: readonly unknown[] },
): string {
  // Only narrow to literal unions for context-independent properties
  if (
    SAFE_LITERAL_PROPS.has(key) &&
    propertyDef.allowedValues &&
    propertyDef.allowedValues.length > 0
  ) {
    const literalValues = propertyDef.allowedValues
      .map((v) => {
        if (typeof v === 'string') return `'${v}'`;
        return String(v);
      })
      .join(' | ');
    return literalValues;
  }

  // Base types for all other properties
  switch (propertyDef.type) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'timestamp':
      return 'string';
    case 'array':
      return 'unknown[]';
    case 'record':
      return 'Record<string, unknown>';
    default:
      return 'unknown';
  }
}

// ── Main ────────────────────────────────────────────────────────────

function generate(): string {
  const events = getAllEventDefinitions();
  const propertyDefs = getAllPropertyDefinitions();

  // Build a lookup map for property definitions
  const propMap = new Map<string, { type: string; allowedValues?: readonly unknown[] }>();
  for (const p of propertyDefs) {
    propMap.set(p.key, p);
  }

  const lines: string[] = [];
  lines.push('// =============================================================================');
  lines.push('// Analytics Platform — Event Registry Interface (AUTO-GENERATED)');
  lines.push('// =============================================================================');
  lines.push('//');
  lines.push('// This file is AUTO-GENERATED by pnpm analytics:typegen --write');
  lines.push('// Do NOT edit manually. Any manual changes will be overwritten.');
  lines.push('//');
  lines.push('// Generated from:');
  lines.push(`//   - ${events.length} event definitions in events/index.ts`);
  lines.push(`//   - ${propertyDefs.length} property definitions in properties/index.ts`);
  lines.push(`//   - ${events.filter((e) => e.status === 'active').length} active events`);
  lines.push(`//   - ${events.filter((e) => e.status === 'deprecated').length} deprecated events`);
  lines.push(`//   - ${events.filter((e) => e.status === 'removed').length} removed events`);
  lines.push('//');
  lines.push('// Maps event name → expected properties (type-safe)');
  lines.push('// This is the contract that track() uses for compile-time validation.');
  lines.push('// =============================================================================');
  lines.push('');
  lines.push('export interface EventRegistry {');

  // Group events by category
  const byCategory = new Map<string, typeof events>();
  for (const event of events) {
    const category = event.category;
    if (!byCategory.has(category)) {
      byCategory.set(category, []);
    }
    byCategory.get(category)!.push(event);
  }

  const sortedCategories = Array.from(byCategory.keys()).sort();

  for (const category of sortedCategories) {
    const categoryEvents = byCategory.get(category)!;
    const categoryLabel = toPascalCase(category);

    lines.push('');
    lines.push(`  // ── ${categoryLabel} ───────────────────────────────────────`);

    for (const event of categoryEvents) {
      const props: string[] = [];

      // Required properties
      for (const key of event.properties.required) {
        const propDef = propMap.get(key);
        const tsType = propDef ? propertyToTypeString(key, propDef) : 'unknown';
        props.push(`    ${key}: ${tsType}`);
      }

      // Optional properties
      for (const key of event.properties.optional) {
        const propDef = propMap.get(key);
        const tsType = propDef ? propertyToTypeString(key, propDef) : 'unknown';
        props.push(`    ${key}?: ${tsType}`);
      }

      // Build the property type line
      if (props.length === 0) {
        // No properties — use never-typed object
        lines.push(`  ${event.name}: Record<string, never>`);
      } else if (props.length === 1) {
        // Single property — inline
        lines.push(`  ${event.name}: { ${props[0]!.trim()} }`);
      } else {
        // Multiple properties — multi-line object
        lines.push(`  ${event.name}: {`);
        for (const prop of props) {
          lines.push(prop);
        }
        lines.push('  }');
      }

      // Add comment for deprecated/removed events
      if (event.status === 'deprecated') {
        lines[lines.length - 1] =
          `${lines[lines.length - 1]} // @deprecated ${event.changelog ?? 'Will be removed'}`.trim();
      } else if (event.status === 'removed') {
        lines[lines.length - 1] =
          `${lines[lines.length - 1]} // @removed ${event.changelog ?? 'No longer available'}`.trim();
      }
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ── Entrypoint ─────────────────────────────────────────────────────

const output = generate();
const args = process.argv.slice(2);
const shouldWrite = args.includes('--write');

if (shouldWrite) {
  const targetPath = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../src/registry/events.generated.ts',
  );
  // Create directory if needed
  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, output, 'utf-8');
  console.log(`\n  ✅ Generated EventRegistry → ${targetPath}`);
  console.log(
    `  📊 ${getAllEventDefinitions().length} events, ${getAllPropertyDefinitions().length} properties\n`,
  );
} else {
  console.log(output);
  console.log(
    `\n  📊 ${getAllEventDefinitions().length} events, ${getAllPropertyDefinitions().length} properties`,
  );
  console.log('  💡 Run with --write to overwrite src/registry/events.generated.ts\n');
}
